### ISSUE TITLE
Include source code in the repository

### ISSUE THREAD

**Issue by hechth** [scannotation/Scannotation_software#1]
To improve transparency in obtained annotations and as a contribution to open science, would it be possible to include the source code for the tool in this repository?

This open up the possibility to contribute for the scientific community and to harden the codebase by getting contributions from developers in the open-source community.

**Comment by scannotation** [comment]
Dear hechth, 
Thanks for providing us some inputs. The way Scannotation generates pre-annotations is transparent and described in the tutorial and the 2 papers associated with this development (cf. READ ME.md). Scannotation was registered with the Agence de Protection des Programmes (french programs protection agency) with an Open Access license and not an Open Source one. Therefore, we are not able to provide the source code at this time.
We are still working on Scannotation and plan to implement a version of it in a Galaxy framework within the next few months. Moreover, we are always open to contributions from the community in the form of questions or suggestions to improve the software.

**Comment by hechth** [comment]
I don't thinking making the tool available via Galaxy in this state is possible.

**Comment by yguitton** [comment]
Hi @hechth 

Do you mean that if the code is not open source it will be impossible to create the Galaxy wrapers and push them to the toolshed ?
Not sure at all, but can Docker Image be a starting point?

Best Yann
